name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows-x64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Setup Clang
      uses: egor-tensin/setup-clang@v1
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
    - name: Cmake setup Debug
      run: cmake --preset debug
    - name: Cmake setup Release
      run: cmake --preset release
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build --no-restore -p:NoGen=true;
    - name: Build Release
      run: dotnet build --no-restore -p:NoGen=true; -c Release
    - uses: actions/upload-artifact@v4
      with:
        name: 'managed'
        path: ./Coplt.Graphics.Core/bin/Release/*.nupkg
        overwrite: true
    - uses: actions/upload-artifact@v4
      with:
        name: 'native-d3d12-debug'
        path: ./Coplt.Graphics.Native.D3d12/bin/Debug/*.nupkg
        overwrite: true
    - uses: actions/upload-artifact@v4
      with:
        name: 'native-d3d12-release'
        path: ./Coplt.Graphics.Native.D3d12/bin/Release/*.nupkg
        overwrite: true
